INSERT INTO USUARIO( ID,NOMBRE , APELLIDOS , PASSWORD , NUMERO , CORREO , ADMINISTRADOR ) VALUES (1,'Pedro','Sxnchxz','moncloa22','32123456789','presidente@spain.es',true);
INSERT INTO USUARIO( ID,NOMBRE , APELLIDOS , PASSWORD , NUMERO , CORREO , ADMINISTRADOR ) VALUES (2,'Nadia','Calvinxo','paris832','32123456987','vicepresidenta@spain.es',false);

//Sentencias Autobuses
    //DESTINO MADRID
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 0,false, 'Madrid', 0800,'2837JHK', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 1,false, 'Madrid', 1200,'2227MHG', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 2,false, 'Madrid', 1600,'2937ACC', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 3,true, 'Madrid', 2000,'9817DOP', 40);

    //DESTINO VALENCIA
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 4,false, 'Valencia', 0800,'2837AAA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 5,false, 'Valencia', 1200,'2227BAB', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 6,false, 'Valencia', 1600,'2937ABA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 7,true, 'Valencia', 2000,'9817TDF', 40);

    //DESTINO BARCELONA
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 8,false, 'Barcelona', 0800,'9124HAS', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 9,false, 'Barcelona', 1200,'1021DXA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 10,false, 'Barcelona', 1600,'1293NSA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 11,true, 'Barcelona', 2000,'9659CEA', 40);

    //DESTINO BILBAO
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 12,false, 'Bilbao', 0800,'6659MAW', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 13,false, 'Bilbao', 1200,'1891DXA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 14,false, 'Bilbao', 1600,'6393NSA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 15,true, 'Bilbao', 2000,'0059CEA', 40);