INSERT INTO USUARIO( ID,NOMBRE , APELLIDOS , PASSWORD , NUMERO , CORREO , ADMINISTRADOR ) VALUES (1,'Pedro','Sxnchxz','moncloa22','32123456789','presidente@spain.es',true);
INSERT INTO USUARIO( ID,NOMBRE , APELLIDOS , PASSWORD , NUMERO , CORREO , ADMINISTRADOR ) VALUES (2,'Nadia','Calvinxo','paris832','32123456987','vicepresidenta@spain.es',false);

//Sentencias Autobuses
    //DESTINO MADRID
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 0,false, 'Madrid', 08,'2837JHK', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 1,false, 'Madrid', 12,'2227MHG', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 2,false, 'Madrid', 16,'2937ACC', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 3,true, 'Madrid', 20,'9817DOP', 40);

    //DESTINO VALENCIA
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 4,false, 'Valencia', 08,'2837AAA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 5,false, 'Valencia', 12,'2227BAB', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 6,false, 'Valencia', 16,'2937ABA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 7,true, 'Valencia', 20,'9817TDF', 40);

    //DESTINO BARCELONA
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 8,false, 'Barcelona', 08,'9124HAS', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 9,false, 'Barcelona', 12,'1021DXA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 10,false, 'Barcelona', 16,'1293NSA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 11,true, 'Barcelona', 20,'9659CEA', 40);

    //DESTINO BILBAO
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 12,false, 'Bilbao', 08,'6659MAW', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 13,false, 'Bilbao', 12,'1891DXA', 40);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 14,false, 'Bilbao', 16,'6393NSA', 0);
INSERT INTO AUTOBUS(ID, AVERIADO, CIUDAD_DESTINO, HORA_SALIDA, MATRICULA, PLAZAS ) VALUES ( 15,true, 'Bilbao', 20,'0059CEA', 40);